apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kine
    tier: control-plane
  name: kine
  namespace: kube-system
spec:
  containers:
  - args:
    - --server-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --server-key-file=/etc/kubernetes/pki/apiserver.key
    - --endpoint=nats://localhost:4222?noEmbed=true
    - --debug
    image: rancher/kine:v0.11.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /metrics
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /metrics
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
