apiVersion: v1
kind: Pod
metadata:
  labels:
    component: nats
    tier: control-plane
  name: nats
  namespace: kube-system
spec:
  containers:
  - args:
    - --port=4222
    - --http_port=8222
    - --jetstream
    - --store_dir=/var/lib/jetstream
    - -DV
    image: nats:2.10.5
    livenessProbe:
      failureThreshold: 8
      httpGet:
        path: /healthz
        port: 8222
      initialDelaySeconds: 10
      timeoutSeconds: 15
    name: nats
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 24
      httpGet:
        path: /healthz
        port: 8222
      initialDelaySeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/jetstream
      name: nats-jetstream-data
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /var/lib/jetstream
      type: DirectoryOrCreate
    name: nats-jetstream-data
